# Generated by Django 2.1.7 on 2019-11-10 01:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fukushu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='totomodel',
            name='duedate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totomodel',
            name='priority',
            field=models.CharField(choices=[('success', 'AC'), ('warning', 'MISS'), ('danger', 'NOSOB'), ('secondry', 'NOCHARENGE'), ('dark', 'IMPOSSIBLE')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
