# Generated by Django 2.1.7 on 2019-11-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fukushu', '0003_auto_20191110_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totomodel',
            name='priority',
            field=models.CharField(choices=[('success', 'AC'), ('warning', 'MISS'), ('danger', 'NOSUB'), ('secondry', 'NOCHARENGE'), ('dark', 'IMPOSSIBLE'), ('no', 'NOTHING')], max_length=50),
        ),
    ]
