# Generated by Django 2.1.7 on 2019-11-10 02:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fukushu', '0004_auto_20191110_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totomodel',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='totomodel',
            name='priority',
        ),
        migrations.AddField(
            model_name='totomodel',
            name='problem3',
            field=models.CharField(choices=[('success', 'AC'), ('warning', 'MISS'), ('danger', 'NOSUB'), ('secondry', 'NOCHARENGE'), ('dark', 'IMPOSSIBLE'), ('link', 'NOTHING')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totomodel',
            name='problem4',
            field=models.CharField(choices=[('success', 'AC'), ('warning', 'MISS'), ('danger', 'NOSUB'), ('secondry', 'NOCHARENGE'), ('dark', 'IMPOSSIBLE'), ('link', 'NOTHING')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totomodel',
            name='probrem1',
            field=models.CharField(choices=[('success', 'AC'), ('warning', 'MISS'), ('danger', 'NOSUB'), ('secondry', 'NOCHARENGE'), ('dark', 'IMPOSSIBLE'), ('link', 'NOTHING')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totomodel',
            name='probrem2',
            field=models.CharField(choices=[('success', 'AC'), ('warning', 'MISS'), ('danger', 'NOSUB'), ('secondry', 'NOCHARENGE'), ('dark', 'IMPOSSIBLE'), ('link', 'NOTHING')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
