# Generated by Django 2.1.7 on 2019-11-10 02:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fukushu', '0006_auto_20191110_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='totomodel',
            old_name='duedate',
            new_name='date1',
        ),
        migrations.AddField(
            model_name='totomodel',
            name='date2',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totomodel',
            name='date3',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totomodel',
            name='date4',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
