# Generated by Django 2.1.7 on 2019-11-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fukushu', '0007_auto_20191110_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totomodel',
            name='problem1',
            field=models.CharField(choices=[('success', 'AC'), ('warning', 'MISS'), ('danger', 'NOSUB'), ('secondary', 'NOCHARENGE'), ('dark', 'IMPOSSIBLE'), ('link', 'NOTHING')], max_length=50),
        ),
        migrations.AlterField(
            model_name='totomodel',
            name='problem2',
            field=models.CharField(choices=[('success', 'AC'), ('warning', 'MISS'), ('danger', 'NOSUB'), ('secondary', 'NOCHARENGE'), ('dark', 'IMPOSSIBLE'), ('link', 'NOTHING')], max_length=50),
        ),
        migrations.AlterField(
            model_name='totomodel',
            name='problem3',
            field=models.CharField(choices=[('success', 'AC'), ('warning', 'MISS'), ('danger', 'NOSUB'), ('secondary', 'NOCHARENGE'), ('dark', 'IMPOSSIBLE'), ('link', 'NOTHING')], max_length=50),
        ),
        migrations.AlterField(
            model_name='totomodel',
            name='problem4',
            field=models.CharField(choices=[('success', 'AC'), ('warning', 'MISS'), ('danger', 'NOSUB'), ('secondary', 'NOCHARENGE'), ('dark', 'IMPOSSIBLE'), ('link', 'NOTHING')], max_length=50),
        ),
    ]
