# Generated by Django 2.1.7 on 2019-11-10 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fukushu', '0008_auto_20191110_1412'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TotoModel',
            new_name='FukushuModel',
        ),
    ]
